sonar.projectKey=taskflow-api
sonar.projectName=Taskflow API
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
